### ISSUE TITLE
Неверное позиционирование последнего пункта меню на экранах меньше 480px

### ISSUE THREAD

**Issue by blackPavlin** [uimini/uimini#4]
В мобильной версии последний пункт меню смещается вправо. 
![sSM2N2tgw8Y](https://user-images.githubusercontent.com/49861726/102949087-da412e80-44e0-11eb-91ef-c9d79e146ece.jpg)

Это вызвано свойством padding-right: 0, которое применяется к последнему элементу списка.

Как можно исправить
```
@media screen and (max-width: 480px) {
  .navbar-item,
  .navbar-link {
    &:last-child {
      padding-right: 20px;
    }
  }
}
```

**Comment by vedees** [comment]
О совсем забыл ответить, спасибо за решение! Я уже обновил весь uimini до второй версии и закрыл все баги!

Ссылки:

- Ссылка на новую документацию (v2) - [клик тут](https://uimini.github.io/docs/)
- Старая документация (v1) **больше не поддерживается** - [клик тут](https://uimini.github.io/docs/v1/get-started)
